version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: hello_docker_backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
    image: hello_docker_frontend
    ports:
      - "80:80"
